# Generated by Django 3.2.11 on 2022-01-25 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dtCreated',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dtModified',
        ),
        migrations.AddField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 7, 50, 47, 998870, tzinfo=utc), verbose_name='date modified'),
        ),
    ]
