# Generated by Django 3.2.11 on 2022-01-25 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220125_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
        ),
    ]
