# Generated by Django 3.2.11 on 2022-01-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category_list',
            field=models.ManyToManyField(to='products.Category'),
        ),
    ]
